apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: type-8
  template:
    metadata:
      labels:
        app: type-8
    spec:
      containers:
        - name: type-8
          image: quay.io/timattt/type-8:latest
          imagePullPolicy: Always
          env:
            - name: REACT_APP_TYPE8_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: type-8-secrets
                  key: type_8_client_id
            - name: REACT_APP_TYPE8_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: type-8-secrets
                  key: type_8_client_secret
            - name: REACT_APP_TYPE8_REDIRECT_URI
              value: https://quiz.mipt.io/code
            - name: REACT_APP_TYPE8_SERVER_IP
              value: https://sso.mipt.io
            - name: HTTPS
              value: "false"
